using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Console;

namespace WaveDodger2
{
    /// <summary>
    /// Class defines a Coin that can be used in a console game. It can be drawn on screen, collected, 
    /// and put into an array generated by the class.
    /// External Dependencies: Player.cs, GameArea.cs
    /// </summary>
    class Coin
    {
        public const char DEFAULT_COIN_CHAR = 'o'; //The ASCII character that represents the coin. 
        private char _coinChar;

        public const ConsoleColor DEFAULT_COIN_FORECOLOR = ConsoleColor.Yellow;
        public const ConsoleColor DEFAULT_COIN_BACKCOLOR = ConsoleColor.DarkYellow;
        private ConsoleColor _coinForeColor; //The foreground color of the coin character. 
        private ConsoleColor _coinBackColor; //The background color of the coin character.
        private int _coinXPos; //The horizontal position of the coin on the screen.
        private int _coinYPos; //The vertical position of the coin on the screen.

        private const bool DEFAULT_COLLECTED_VALUE = false;
        private bool _collected; // Determines whether the coin has already been collected by the player or not (see Player.cs).


        #region//CONSTRUCTORS
        /// <summary>
        /// Sets the _coinChar, _coinForeColor, _coinBackColor, and _collected properties to their default values. 
        /// Sets X and Y positions to 0.
        /// </summary>
        public Coin()//default settings
        {
            CoinChar = DEFAULT_COIN_CHAR;
            CoinForeColor = DEFAULT_COIN_FORECOLOR;
            CoinBackColor = DEFAULT_COIN_BACKCOLOR;
            CoinXPos = 0;
            CoinYPos = 0;
            Collected = DEFAULT_COLLECTED_VALUE;
        }

        /// <summary>
        /// Sets _coinChar, _coinForeColor, _coinBackColor to the arguments provided, sets X and Y positions to 
        /// 0 and the _collected status to its default value.
        /// </summary>
        /// <param name="coinChar_"></param>
        /// <param name="coinForeColor_"></param>
        /// <param name="coinBackColor_"></param>
        public Coin(char coinChar_, ConsoleColor coinForeColor_, ConsoleColor coinBackColor_) //advanced editor
        {
            CoinChar = coinChar_;
            CoinForeColor = coinForeColor_;
            CoinBackColor = coinBackColor_;
            CoinXPos = 0;
            CoinYPos = 0;
            Collected = DEFAULT_COLLECTED_VALUE;
        }
        #endregion

        #region//EXTERNAL METHODS

        /// <summary>
        /// Takes no arguments. Checks to see if the coin has been collected already, and if not,
        /// writes it on screen in the correct colors. Returns void.
        /// </summary>
        public void WriteOnScreen()
        {
            if (!Collected)
            {
                SetCursorPosition(CoinXPos, CoinYPos);
                ForegroundColor = CoinForeColor;
                BackgroundColor = CoinBackColor;
                WriteLine(CoinChar);
                ResetColor();
            }
        }

        /// <summary>
        /// Takes a player instance as its only argument. Sets the coin’s Collected status to true,
        /// and increases the player’s coins collected by one.
        /// </summary>
        /// <param name="player"></param>
        public void Collect(Player player)
        {
            Collected = true;
            player.CoinsCollected++;
        }

        /// <summary>
        /// Overload takes the number of coins, a Random class instance, the game’s play area and the player object, 
        /// and generates an array of coins of the specified size numberOfCoins. All of the coins are initialized using 
        /// the default constructor. Ensures no coins spawn on top of the player. Returns the array.
        /// </summary>
        /// <param name="numberOfCoins"></param>
        /// <param name="rnd"></param>
        /// <param name="area"></param>
        /// <param name="player"></param>
        /// <returns></returns>
        public static Coin[] GenerateCoinArray(int numberOfCoins, Random rnd, GameArea area, Player player)
        {
            Coin[] coins = new Coin[numberOfCoins];
            int tempX;
            int tempY;

            for (int i = 0; i < coins.Length; i++)
                coins[i] = new Coin();

            coins[0].CoinXPos = rnd.Next(area.LeftLimit, area.RightLimit + 1); 
            coins[0].CoinYPos = rnd.Next(area.UpLimit, area.DownLimit + 1);

            for (int i = 0; i < coins.Length; i++)
            {
                tempX = rnd.Next(area.LeftLimit, area.RightLimit + 1);
                tempY = rnd.Next(area.UpLimit, area.DownLimit + 1);

                for(int j = 0; j < i; j++)
                {      //ensures coins dont spawn on top of each other                  //ensures coins dont spawn on top of the player
                    if ((tempX != coins[j].CoinXPos && tempY != coins[j].CoinYPos) && (tempY != player.XPos && tempY != player.YPos))
                    {
                        coins[i].CoinXPos = tempX;
                        coins[i].CoinYPos = tempY;
                    }
                    else
                    {
                        i--;
                    }
                }
            }
            return coins;
        }

        /// <summary>
        /// Overload takes the number of coins, a Random class instance, the game’s play area and the player object,
        /// a coin character along with a coin foreground and background color. Generates an array of coins of the 
        /// specified size numberOfCoins. All of the coins are initialized using the triple-parameter constructor. 
        /// Ensures no coins spawn on top of the player. Returns the array.
        /// </summary>
        /// <param name="numberOfCoins"></param>
        /// <param name="rnd"></param>
        /// <param name="area"></param>
        /// <param name="player"></param>
        /// <param name="coinChar"></param>
        /// <param name="coinForeColor"></param>
        /// <param name="coinBackColor"></param>
        /// <returns></returns>
        public static Coin[] GenerateCoinArray(int numberOfCoins, Random rnd, GameArea area, Player player, char coinChar, ConsoleColor coinForeColor, ConsoleColor coinBackColor)
        {
            Coin[] coins = new Coin[numberOfCoins];
            int tempX;
            int tempY;

            for (int i = 0; i < coins.Length; i++)
                coins[i] = new Coin(coinChar, coinForeColor, coinBackColor);

            coins[0].CoinXPos = rnd.Next(area.LeftLimit, area.RightLimit + 1);
            coins[0].CoinYPos = rnd.Next(area.UpLimit, area.DownLimit + 1);

            for (int i = 0; i < coins.Length; i++)
            {
                tempX = rnd.Next(area.LeftLimit, area.RightLimit + 1);
                tempY = rnd.Next(area.UpLimit, area.DownLimit + 1);

                for (int j = 0; j < i; j++)
                {      //ensures coins dont spawn on top of each other                  //ensures coins dont spawn on top of the player
                    if ((tempX != coins[j].CoinXPos && tempY != coins[j].CoinYPos) && (tempY != player.XPos && tempY != player.YPos))
                    {
                        coins[i].CoinXPos = tempX;
                        coins[i].CoinYPos = tempY;
                    }
                    else
                    {
                        i--;
                    }
                }
            }
            return coins;
        }

        /// <summary>
        /// Takes an array of coins as an argument, and writes all of the elements of the array in their correct 
        /// positions and correct colors. Returns void.
        /// </summary>
        /// <param name="coins"></param>
        public static void Render(Coin[] coins)
        {
            for (int i = 0; i < coins.Length; i++)
            {
                coins[i].WriteOnScreen();
            }
        }

        /// <summary>
        /// Takes an array of coins as an argument, and sets each element’s Collected property to false. Returns void.
        /// </summary>
        /// <param name="coins"></param>
        public static void Reset(Coin[] coins)
        {
            foreach (Coin c in coins)
            {
                c.Collected = false;
            }
        }
        #endregion

        #region//PROPERTIES
        public char CoinChar
        {
            get
            {
                return _coinChar;
            }
            set
            {
                _coinChar = value;
            }
        }

        public ConsoleColor CoinForeColor
        {
            get
            {
                return _coinForeColor;
            }
            set
            {
                _coinForeColor = value;
            }
        }

        public ConsoleColor CoinBackColor
        {
            get
            {
                return _coinBackColor;
            }
            set
            {
                _coinBackColor = value;
            }
        }

        public int CoinXPos
        {
            get
            {
                return _coinXPos;
            }
            set
            {
                if (value < 0)
                    throw new ArgumentException("COIN X POSITION CANNOT BE NEGATIVE","_coinXPos");

                _coinXPos = value;
            }
        }

        public int CoinYPos
        {
            get
            {
                return _coinYPos;
            }
            set
            {
                if (value < 0)
                    throw new ArgumentException("COIN Y POSITION CANNOT BE NEGATIVE", "_coinYPos");

                _coinYPos = value;
            }
        }

        public bool Collected
        {
            get
            {
                return _collected;
            }
            set
            {
                _collected = value;
            }
        }


        #endregion
    }
}
